Song.create(name: "LYCKA", artist: "Eric Prydz", genre: "electronic")
Song.create(name: "Heroes", artist: "Alesso", genre: "electronic")
Song.create(name: "Levels", artist: "Avicii", genre: "electronic")
Song.create(name: "C.R.E.A.M", artist: "Wu-Tang Clan", genre: "rap")
Song.create(name: "Gin and Juice", artist: "Snoop Dogg", genre: "rap")
Song.create(name: "Sorry", artist: "Justin Bieber", genre: "pop")
Song.create(name: "Company", artist: "Justin Bieber", genre: "pop")
